name: Continuous Integration
on: [push, pull_request]
jobs:
  test:
    name: Test with Node.js v${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: ["10", "12", "13", "14"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependancies
        run: yarn install --frozen-lockfile
      - name: Lint the source
        run: yarn lint
      - name: Transpile into dist
        run: yarn build
      - name: Run tests
        run: yarn test
